[build-system]
requires = ["maturin>=1.15,<2.0"]
build-backend = "maturin"

[project]
name = "wintask"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]

[dependency-groups]
docs = [
    "mkdocs>=1.6,<2.0",
]

[tool.maturin]
module-name = "wintask._wintask_backend"
python-source = "python"
include = [{ path = "python/wintask/py.typed", format = "wheel" }]
